version: '3.7'
services:

    dqc:
        build:
            context: .
            dockerfile: Dockerfile.dev
        image: dqc_dev
        command: tail -f /dev/null
        tty: true
        volumes:
            - .:/dfast_qc
            # ダウンロード用データ、gmap DBの置き場所
            - ../../../dfast_volumes/dqc_reference:/dqc_reference  # for dev.
        working_dir: /dfast_qc         
